######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 14:06:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
