######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 09:34:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += mywidget.h
SOURCES += list.cpp mywidget.cpp
