######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 18 20:02:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digitalclock.h
SOURCES += digitalclock.cpp main.cpp
