######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 17:09:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QFile.cpp
