######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 11:39:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pushbutton_slider_lcd.cpp
