######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 18 17:10:47 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h ui_mydialog.h
SOURCES += main.cpp mydialog.cpp
