######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 17:38:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pushbutton3.cpp
