######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 19:46:39 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lcdrange.h
SOURCES += lcdmain.cpp lcdrange.cpp
