######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 09:36:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += main.h
SOURCES += main.cpp
