######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 10:45:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pushbutton1.cpp
