######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 20:59:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
FORMS += mydialog.ui
SOURCES += main.cpp mydialog.cpp
