######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 17:07:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dir.cpp
